// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.1
// source: aesearch.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AesearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AesearchResponse) Reset() {
	*x = AesearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aesearch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AesearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AesearchResponse) ProtoMessage() {}

func (x *AesearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aesearch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AesearchResponse.ProtoReflect.Descriptor instead.
func (*AesearchResponse) Descriptor() ([]byte, []int) {
	return file_aesearch_proto_rawDescGZIP(), []int{0}
}

func (x *AesearchResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Listing []*AesearchItemResponse `protobuf:"bytes,1,rep,name=listing,proto3" json:"listing,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aesearch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_aesearch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_aesearch_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetListing() []*AesearchItemResponse {
	if x != nil {
		return x.Listing
	}
	return nil
}

type AesearchItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Host  string  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Descr string  `protobuf:"bytes,3,opt,name=descr,proto3" json:"descr,omitempty"`
	Icon  string  `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Image string  `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Url   string  `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Pixel string  `protobuf:"bytes,7,opt,name=pixel,proto3" json:"pixel,omitempty"`
	Bid   float64 `protobuf:"fixed64,8,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *AesearchItemResponse) Reset() {
	*x = AesearchItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aesearch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AesearchItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AesearchItemResponse) ProtoMessage() {}

func (x *AesearchItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aesearch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AesearchItemResponse.ProtoReflect.Descriptor instead.
func (*AesearchItemResponse) Descriptor() ([]byte, []int) {
	return file_aesearch_proto_rawDescGZIP(), []int{2}
}

func (x *AesearchItemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AesearchItemResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *AesearchItemResponse) GetDescr() string {
	if x != nil {
		return x.Descr
	}
	return ""
}

func (x *AesearchItemResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *AesearchItemResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AesearchItemResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AesearchItemResponse) GetPixel() string {
	if x != nil {
		return x.Pixel
	}
	return ""
}

func (x *AesearchItemResponse) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

var File_aesearch_proto protoreflect.FileDescriptor

var file_aesearch_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x33, 0x0a, 0x10, 0x41, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x39, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2f, 0x0a, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x41, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x6c, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x22, 0xba, 0x01, 0x0a, 0x14, 0x41, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x73, 0x63, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x73, 0x63, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x62,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x62, 0x69, 0x64, 0x42, 0x1e, 0x5a,
	0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x78, 0x79, 0x64,
	0x2d, 0x69, 0x6f, 0x2f, 0x66, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aesearch_proto_rawDescOnce sync.Once
	file_aesearch_proto_rawDescData = file_aesearch_proto_rawDesc
)

func file_aesearch_proto_rawDescGZIP() []byte {
	file_aesearch_proto_rawDescOnce.Do(func() {
		file_aesearch_proto_rawDescData = protoimpl.X.CompressGZIP(file_aesearch_proto_rawDescData)
	})
	return file_aesearch_proto_rawDescData
}

var file_aesearch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aesearch_proto_goTypes = []interface{}{
	(*AesearchResponse)(nil),     // 0: AesearchResponse
	(*Result)(nil),               // 1: Result
	(*AesearchItemResponse)(nil), // 2: AesearchItemResponse
}
var file_aesearch_proto_depIdxs = []int32{
	1, // 0: AesearchResponse.result:type_name -> Result
	2, // 1: Result.listing:type_name -> AesearchItemResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aesearch_proto_init() }
func file_aesearch_proto_init() {
	if File_aesearch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aesearch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AesearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aesearch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aesearch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AesearchItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aesearch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aesearch_proto_goTypes,
		DependencyIndexes: file_aesearch_proto_depIdxs,
		MessageInfos:      file_aesearch_proto_msgTypes,
	}.Build()
	File_aesearch_proto = out.File
	file_aesearch_proto_rawDesc = nil
	file_aesearch_proto_goTypes = nil
	file_aesearch_proto_depIdxs = nil
}
