// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: api/evadav.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EvadavPopunderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link string  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Cpc  float64 `protobuf:"fixed64,2,opt,name=cpc,proto3" json:"cpc,omitempty"`
}

func (x *EvadavPopunderResponse) Reset() {
	*x = EvadavPopunderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_evadav_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvadavPopunderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvadavPopunderResponse) ProtoMessage() {}

func (x *EvadavPopunderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evadav_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvadavPopunderResponse.ProtoReflect.Descriptor instead.
func (*EvadavPopunderResponse) Descriptor() ([]byte, []int) {
	return file_api_evadav_proto_rawDescGZIP(), []int{0}
}

func (x *EvadavPopunderResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *EvadavPopunderResponse) GetCpc() float64 {
	if x != nil {
		return x.Cpc
	}
	return 0
}

type EvadavPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Descr string  `protobuf:"bytes,3,opt,name=descr,proto3" json:"descr,omitempty"`
	Icon  string  `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Image string  `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Link  string  `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	Cpc   float64 `protobuf:"fixed64,7,opt,name=cpc,proto3" json:"cpc,omitempty"`
}

func (x *EvadavPushResponse) Reset() {
	*x = EvadavPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_evadav_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvadavPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvadavPushResponse) ProtoMessage() {}

func (x *EvadavPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_evadav_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvadavPushResponse.ProtoReflect.Descriptor instead.
func (*EvadavPushResponse) Descriptor() ([]byte, []int) {
	return file_api_evadav_proto_rawDescGZIP(), []int{1}
}

func (x *EvadavPushResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvadavPushResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *EvadavPushResponse) GetDescr() string {
	if x != nil {
		return x.Descr
	}
	return ""
}

func (x *EvadavPushResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *EvadavPushResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *EvadavPushResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *EvadavPushResponse) GetCpc() float64 {
	if x != nil {
		return x.Cpc
	}
	return 0
}

var File_api_evadav_proto protoreflect.FileDescriptor

var file_api_evadav_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x76, 0x61, 0x64, 0x61, 0x76, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x16, 0x45, 0x76, 0x61, 0x64, 0x61, 0x76, 0x50, 0x6f, 0x70, 0x75,
	0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x63,
	0x70, 0x63, 0x22, 0xa0, 0x01, 0x0a, 0x12, 0x45, 0x76, 0x61, 0x64, 0x61, 0x76, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x65, 0x73, 0x63, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x63, 0x70, 0x63, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x78, 0x79, 0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x66, 0x61, 0x6b, 0x65,
	0x72, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_evadav_proto_rawDescOnce sync.Once
	file_api_evadav_proto_rawDescData = file_api_evadav_proto_rawDesc
)

func file_api_evadav_proto_rawDescGZIP() []byte {
	file_api_evadav_proto_rawDescOnce.Do(func() {
		file_api_evadav_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_evadav_proto_rawDescData)
	})
	return file_api_evadav_proto_rawDescData
}

var file_api_evadav_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_evadav_proto_goTypes = []interface{}{
	(*EvadavPopunderResponse)(nil), // 0: EvadavPopunderResponse
	(*EvadavPushResponse)(nil),     // 1: EvadavPushResponse
}
var file_api_evadav_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_evadav_proto_init() }
func file_api_evadav_proto_init() {
	if File_api_evadav_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_evadav_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvadavPopunderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_evadav_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvadavPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_evadav_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_evadav_proto_goTypes,
		DependencyIndexes: file_api_evadav_proto_depIdxs,
		MessageInfos:      file_api_evadav_proto_msgTypes,
	}.Build()
	File_api_evadav_proto = out.File
	file_api_evadav_proto_rawDesc = nil
	file_api_evadav_proto_goTypes = nil
	file_api_evadav_proto_depIdxs = nil
}
