// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.1
// source: ford.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FordPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *FordPushItemResponse `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FordPushResponse) Reset() {
	*x = FordPushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ford_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FordPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FordPushResponse) ProtoMessage() {}

func (x *FordPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ford_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FordPushResponse.ProtoReflect.Descriptor instead.
func (*FordPushResponse) Descriptor() ([]byte, []int) {
	return file_ford_proto_rawDescGZIP(), []int{0}
}

func (x *FordPushResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FordPushResponse) GetData() *FordPushItemResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type FordPushItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpc         float64 `protobuf:"fixed64,1,opt,name=cpc,proto3" json:"cpc,omitempty"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon        string  `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Image       string  `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Link        string  `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *FordPushItemResponse) Reset() {
	*x = FordPushItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ford_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FordPushItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FordPushItemResponse) ProtoMessage() {}

func (x *FordPushItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ford_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FordPushItemResponse.ProtoReflect.Descriptor instead.
func (*FordPushItemResponse) Descriptor() ([]byte, []int) {
	return file_ford_proto_rawDescGZIP(), []int{1}
}

func (x *FordPushItemResponse) GetCpc() float64 {
	if x != nil {
		return x.Cpc
	}
	return 0
}

func (x *FordPushItemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FordPushItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FordPushItemResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *FordPushItemResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *FordPushItemResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

var File_ford_proto protoreflect.FileDescriptor

var file_ford_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x55, 0x0a, 0x10,
	0x46, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x46, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73,
	0x68, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x9e, 0x01, 0x0a, 0x14, 0x46, 0x6f, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x70, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x63, 0x70, 0x63, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x78, 0x79, 0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x66, 0x61, 0x6b, 0x65, 0x72,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ford_proto_rawDescOnce sync.Once
	file_ford_proto_rawDescData = file_ford_proto_rawDesc
)

func file_ford_proto_rawDescGZIP() []byte {
	file_ford_proto_rawDescOnce.Do(func() {
		file_ford_proto_rawDescData = protoimpl.X.CompressGZIP(file_ford_proto_rawDescData)
	})
	return file_ford_proto_rawDescData
}

var file_ford_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ford_proto_goTypes = []interface{}{
	(*FordPushResponse)(nil),     // 0: FordPushResponse
	(*FordPushItemResponse)(nil), // 1: FordPushItemResponse
}
var file_ford_proto_depIdxs = []int32{
	1, // 0: FordPushResponse.data:type_name -> FordPushItemResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ford_proto_init() }
func file_ford_proto_init() {
	if File_ford_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ford_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FordPushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ford_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FordPushItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ford_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ford_proto_goTypes,
		DependencyIndexes: file_ford_proto_depIdxs,
		MessageInfos:      file_ford_proto_msgTypes,
	}.Build()
	File_ford_proto = out.File
	file_ford_proto_rawDesc = nil
	file_ford_proto_goTypes = nil
	file_ford_proto_depIdxs = nil
}
