// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.1
// source: jaguar.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type JaguarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Articles []*JaguarItemResponse `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
}

func (x *JaguarResponse) Reset() {
	*x = JaguarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jaguar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JaguarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JaguarResponse) ProtoMessage() {}

func (x *JaguarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaguar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JaguarResponse.ProtoReflect.Descriptor instead.
func (*JaguarResponse) Descriptor() ([]byte, []int) {
	return file_jaguar_proto_rawDescGZIP(), []int{0}
}

func (x *JaguarResponse) GetArticles() []*JaguarItemResponse {
	if x != nil {
		return x.Articles
	}
	return nil
}

type JaguarItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerId      int64   `protobuf:"varint,1,opt,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	CampaignId    int64   `protobuf:"varint,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Title         string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text          string  `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Icon          string  `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Image         string  `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	ClickUrl      string  `protobuf:"bytes,7,opt,name=click_url,json=clickUrl,proto3" json:"click_url,omitempty"`
	ImpressionUrl string  `protobuf:"bytes,8,opt,name=impression_url,json=impressionUrl,proto3" json:"impression_url,omitempty"`
	CpcRate       float64 `protobuf:"fixed64,9,opt,name=cpc_rate,json=cpcRate,proto3" json:"cpc_rate,omitempty"`
	Rate          float64 `protobuf:"fixed64,10,opt,name=rate,proto3" json:"rate,omitempty"`
	RateModel     string  `protobuf:"bytes,11,opt,name=rate_model,json=rateModel,proto3" json:"rate_model,omitempty"`
	Code          int64   `protobuf:"varint,12,opt,name=code,proto3" json:"code,omitempty"`
	Message       string  `protobuf:"bytes,13,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JaguarItemResponse) Reset() {
	*x = JaguarItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jaguar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JaguarItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JaguarItemResponse) ProtoMessage() {}

func (x *JaguarItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jaguar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JaguarItemResponse.ProtoReflect.Descriptor instead.
func (*JaguarItemResponse) Descriptor() ([]byte, []int) {
	return file_jaguar_proto_rawDescGZIP(), []int{1}
}

func (x *JaguarItemResponse) GetBannerId() int64 {
	if x != nil {
		return x.BannerId
	}
	return 0
}

func (x *JaguarItemResponse) GetCampaignId() int64 {
	if x != nil {
		return x.CampaignId
	}
	return 0
}

func (x *JaguarItemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JaguarItemResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *JaguarItemResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *JaguarItemResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *JaguarItemResponse) GetClickUrl() string {
	if x != nil {
		return x.ClickUrl
	}
	return ""
}

func (x *JaguarItemResponse) GetImpressionUrl() string {
	if x != nil {
		return x.ImpressionUrl
	}
	return ""
}

func (x *JaguarItemResponse) GetCpcRate() float64 {
	if x != nil {
		return x.CpcRate
	}
	return 0
}

func (x *JaguarItemResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *JaguarItemResponse) GetRateModel() string {
	if x != nil {
		return x.RateModel
	}
	return ""
}

func (x *JaguarItemResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JaguarItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_jaguar_proto protoreflect.FileDescriptor

var file_jaguar_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6a, 0x61, 0x67, 0x75, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41,
	0x0a, 0x0e, 0x4a, 0x61, 0x67, 0x75, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2f, 0x0a, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4a, 0x61, 0x67, 0x75, 0x61, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x73, 0x22, 0xe6, 0x02, 0x0a, 0x12, 0x4a, 0x61, 0x67, 0x75, 0x61, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c,
	0x69, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x69, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x19,
	0x0a, 0x08, 0x63, 0x70, 0x63, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x63, 0x70, 0x63, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x72, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x78, 0x79, 0x64, 0x2d, 0x69, 0x6f,
	0x2f, 0x66, 0x61, 0x6b, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_jaguar_proto_rawDescOnce sync.Once
	file_jaguar_proto_rawDescData = file_jaguar_proto_rawDesc
)

func file_jaguar_proto_rawDescGZIP() []byte {
	file_jaguar_proto_rawDescOnce.Do(func() {
		file_jaguar_proto_rawDescData = protoimpl.X.CompressGZIP(file_jaguar_proto_rawDescData)
	})
	return file_jaguar_proto_rawDescData
}

var file_jaguar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jaguar_proto_goTypes = []interface{}{
	(*JaguarResponse)(nil),     // 0: JaguarResponse
	(*JaguarItemResponse)(nil), // 1: JaguarItemResponse
}
var file_jaguar_proto_depIdxs = []int32{
	1, // 0: JaguarResponse.articles:type_name -> JaguarItemResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jaguar_proto_init() }
func file_jaguar_proto_init() {
	if File_jaguar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jaguar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JaguarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jaguar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JaguarItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jaguar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jaguar_proto_goTypes,
		DependencyIndexes: file_jaguar_proto_depIdxs,
		MessageInfos:      file_jaguar_proto_msgTypes,
	}.Build()
	File_jaguar_proto = out.File
	file_jaguar_proto_rawDesc = nil
	file_jaguar_proto_goTypes = nil
	file_jaguar_proto_depIdxs = nil
}
