// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.1
// source: peugeot.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PeugeotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*PeugeotItemResponse `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *PeugeotResponse) Reset() {
	*x = PeugeotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peugeot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeugeotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeugeotResponse) ProtoMessage() {}

func (x *PeugeotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peugeot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeugeotResponse.ProtoReflect.Descriptor instead.
func (*PeugeotResponse) Descriptor() ([]byte, []int) {
	return file_peugeot_proto_rawDescGZIP(), []int{0}
}

func (x *PeugeotResponse) GetResult() []*PeugeotItemResponse {
	if x != nil {
		return x.Result
	}
	return nil
}

type PeugeotItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpc         float64 `protobuf:"fixed64,1,opt,name=cpc,proto3" json:"cpc,omitempty"`
	Url         string  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title       string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Icon        string  `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Image       string  `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	AdId        string  `protobuf:"bytes,7,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
}

func (x *PeugeotItemResponse) Reset() {
	*x = PeugeotItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peugeot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeugeotItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeugeotItemResponse) ProtoMessage() {}

func (x *PeugeotItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peugeot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeugeotItemResponse.ProtoReflect.Descriptor instead.
func (*PeugeotItemResponse) Descriptor() ([]byte, []int) {
	return file_peugeot_proto_rawDescGZIP(), []int{1}
}

func (x *PeugeotItemResponse) GetCpc() float64 {
	if x != nil {
		return x.Cpc
	}
	return 0
}

func (x *PeugeotItemResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PeugeotItemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PeugeotItemResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PeugeotItemResponse) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PeugeotItemResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *PeugeotItemResponse) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

var File_peugeot_proto protoreflect.FileDescriptor

var file_peugeot_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x65, 0x75, 0x67, 0x65, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3f, 0x0a, 0x0f, 0x50, 0x65, 0x75, 0x67, 0x65, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x50, 0x65, 0x75, 0x67, 0x65, 0x6f, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0xb0, 0x01, 0x0a, 0x13, 0x50, 0x65, 0x75, 0x67, 0x65, 0x6f, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x63, 0x70, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x13,
	0x0a, 0x05, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x64, 0x49, 0x64, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x78, 0x79, 0x64, 0x2d, 0x69, 0x6f, 0x2f, 0x66, 0x61, 0x6b, 0x65, 0x72, 0x2f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peugeot_proto_rawDescOnce sync.Once
	file_peugeot_proto_rawDescData = file_peugeot_proto_rawDesc
)

func file_peugeot_proto_rawDescGZIP() []byte {
	file_peugeot_proto_rawDescOnce.Do(func() {
		file_peugeot_proto_rawDescData = protoimpl.X.CompressGZIP(file_peugeot_proto_rawDescData)
	})
	return file_peugeot_proto_rawDescData
}

var file_peugeot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_peugeot_proto_goTypes = []interface{}{
	(*PeugeotResponse)(nil),     // 0: PeugeotResponse
	(*PeugeotItemResponse)(nil), // 1: PeugeotItemResponse
}
var file_peugeot_proto_depIdxs = []int32{
	1, // 0: PeugeotResponse.result:type_name -> PeugeotItemResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_peugeot_proto_init() }
func file_peugeot_proto_init() {
	if File_peugeot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peugeot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeugeotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peugeot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeugeotItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peugeot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_peugeot_proto_goTypes,
		DependencyIndexes: file_peugeot_proto_depIdxs,
		MessageInfos:      file_peugeot_proto_msgTypes,
	}.Build()
	File_peugeot_proto = out.File
	file_peugeot_proto_rawDesc = nil
	file_peugeot_proto_goTypes = nil
	file_peugeot_proto_depIdxs = nil
}
