name: Go

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ^${{ matrix.go-version }}
      id: go
    - name: Configure git for private modules
      env:
        USER: ${{ secrets.DOCKER_USER }}
        TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Tests
      run: make tests
    - name: Linters
      run: make linters
