name: Go

on:
  pull_request:
    branches: [ master ]

env:
  USER: ${{ secrets.DOCKER_USER }}
  TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ^${{ matrix.go-version }}
      id: go
    - name: Configure git for private modules
      run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: make build
    - name: Tests
      run: make tests
    - name: Lint
      run: make lint
      continue-on-error: true
